-- Script de banco para o prototipo Censo 2025 (H2)
-- Estrategia:
-- 1) Tabelas principais (usuario, aluno, curso, curso_aluno)
-- 2) Tabelas de catalogo (dominio_opcao) para campos 1..N
-- 3) Tabelas auxiliares de vinculo de opcoes por modulo
-- 4) Metadados de leiaute e armazenamento de campos complementares

CREATE TABLE IF NOT EXISTS usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(50) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NOT NULL,
    nome VARCHAR(120) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE usuario ALTER COLUMN senha_hash VARCHAR(255);

CREATE TABLE IF NOT EXISTS aluno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_aluno_inep BIGINT,
    nome VARCHAR(120) NOT NULL,
    cpf CHAR(11) NOT NULL UNIQUE,
    data_nascimento DATE NOT NULL,
    cor_raca SMALLINT,
    nacionalidade SMALLINT NOT NULL,
    uf_nascimento CHAR(2),
    municipio_nascimento VARCHAR(120),
    pais_origem CHAR(3) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS curso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_curso_emec VARCHAR(12) NOT NULL UNIQUE,
    nome VARCHAR(160) NOT NULL,
    nivel_academico VARCHAR(30) NOT NULL,
    formato_oferta VARCHAR(20) NOT NULL,
    curso_teve_aluno_vinculado SMALLINT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS curso_aluno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id BIGINT NOT NULL,
    curso_id BIGINT NOT NULL,
    id_aluno_ies VARCHAR(30) NOT NULL,
    periodo_referencia CHAR(4) NOT NULL,
    codigo_polo_ead VARCHAR(12),
    turno_aluno SMALLINT,
    situacao_vinculo SMALLINT,
    curso_origem VARCHAR(12),
    semestre_conclusao CHAR(6),
    aluno_parfor SMALLINT DEFAULT 0,
    segunda_licenciatura_formacao SMALLINT DEFAULT 0,
    tipo_segunda_licenciatura_formacao SMALLINT,
    semestre_ingresso CHAR(6),
    forma_ingresso_vestibular SMALLINT DEFAULT 0,
    forma_ingresso_enem SMALLINT DEFAULT 0,
    forma_ingresso_avaliacao_seriada SMALLINT DEFAULT 0,
    forma_ingresso_selecao_simplificada SMALLINT DEFAULT 0,
    forma_ingresso_egresso_bi_li SMALLINT DEFAULT 0,
    forma_ingresso_pec_g SMALLINT DEFAULT 0,
    forma_ingresso_transferencia_exofficio SMALLINT DEFAULT 0,
    forma_ingresso_decisao_judicial SMALLINT DEFAULT 0,
    forma_ingresso_vagas_remanescentes SMALLINT DEFAULT 0,
    forma_ingresso_programas_especiais SMALLINT DEFAULT 0,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_curso_aluno_aluno FOREIGN KEY (aluno_id) REFERENCES aluno (id) ON DELETE CASCADE,
    CONSTRAINT fk_curso_aluno_curso FOREIGN KEY (curso_id) REFERENCES curso (id) ON DELETE CASCADE,
    CONSTRAINT uk_curso_aluno UNIQUE (aluno_id, curso_id, periodo_referencia)
);

CREATE TABLE IF NOT EXISTS dominio_opcao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria VARCHAR(60) NOT NULL,
    codigo VARCHAR(30) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_dominio_opcao UNIQUE (categoria, codigo)
);

CREATE TABLE IF NOT EXISTS aluno_opcao (
    aluno_id BIGINT NOT NULL,
    opcao_id BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (aluno_id, opcao_id),
    CONSTRAINT fk_aluno_opcao_aluno FOREIGN KEY (aluno_id) REFERENCES aluno (id) ON DELETE CASCADE,
    CONSTRAINT fk_aluno_opcao_opcao FOREIGN KEY (opcao_id) REFERENCES dominio_opcao (id)
);

CREATE TABLE IF NOT EXISTS curso_opcao (
    curso_id BIGINT NOT NULL,
    opcao_id BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (curso_id, opcao_id),
    CONSTRAINT fk_curso_opcao_curso FOREIGN KEY (curso_id) REFERENCES curso (id) ON DELETE CASCADE,
    CONSTRAINT fk_curso_opcao_opcao FOREIGN KEY (opcao_id) REFERENCES dominio_opcao (id)
);

CREATE TABLE IF NOT EXISTS curso_aluno_opcao (
    curso_aluno_id BIGINT NOT NULL,
    opcao_id BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (curso_aluno_id, opcao_id),
    CONSTRAINT fk_curso_aluno_opcao_curso_aluno FOREIGN KEY (curso_aluno_id) REFERENCES curso_aluno (id) ON DELETE CASCADE,
    CONSTRAINT fk_curso_aluno_opcao_opcao FOREIGN KEY (opcao_id) REFERENCES dominio_opcao (id)
);

CREATE TABLE IF NOT EXISTS layout_campo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modulo VARCHAR(30) NOT NULL,
    numero_campo INTEGER NOT NULL,
    nome_campo VARCHAR(255) NOT NULL,
    obrigatoriedade VARCHAR(20),
    CONSTRAINT uk_layout_campo UNIQUE (modulo, numero_campo)
);

CREATE TABLE IF NOT EXISTS aluno_layout_valor (
    aluno_id BIGINT NOT NULL,
    layout_campo_id BIGINT NOT NULL,
    valor VARCHAR(4000),
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (aluno_id, layout_campo_id),
    CONSTRAINT fk_aluno_layout_valor_aluno FOREIGN KEY (aluno_id) REFERENCES aluno (id) ON DELETE CASCADE,
    CONSTRAINT fk_aluno_layout_valor_layout FOREIGN KEY (layout_campo_id) REFERENCES layout_campo (id)
);

CREATE TABLE IF NOT EXISTS curso_layout_valor (
    curso_id BIGINT NOT NULL,
    layout_campo_id BIGINT NOT NULL,
    valor VARCHAR(4000),
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (curso_id, layout_campo_id),
    CONSTRAINT fk_curso_layout_valor_curso FOREIGN KEY (curso_id) REFERENCES curso (id) ON DELETE CASCADE,
    CONSTRAINT fk_curso_layout_valor_layout FOREIGN KEY (layout_campo_id) REFERENCES layout_campo (id)
);

CREATE TABLE IF NOT EXISTS curso_aluno_layout_valor (
    curso_aluno_id BIGINT NOT NULL,
    layout_campo_id BIGINT NOT NULL,
    valor VARCHAR(4000),
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (curso_aluno_id, layout_campo_id),
    CONSTRAINT fk_curso_aluno_layout_valor_curso_aluno FOREIGN KEY (curso_aluno_id) REFERENCES curso_aluno (id) ON DELETE CASCADE,
    CONSTRAINT fk_curso_aluno_layout_valor_layout FOREIGN KEY (layout_campo_id) REFERENCES layout_campo (id)
);

CREATE TABLE IF NOT EXISTS docente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_docente_ies VARCHAR(20),
    nome VARCHAR(120) NOT NULL,
    cpf CHAR(11) NOT NULL UNIQUE,
    documento_estrangeiro VARCHAR(20),
    data_nascimento DATE NOT NULL,
    cor_raca SMALLINT,
    nacionalidade SMALLINT NOT NULL,
    pais_origem CHAR(3) NOT NULL,
    uf_nascimento SMALLINT,
    municipio_nascimento VARCHAR(7),
    docente_deficiencia SMALLINT,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ies_inep BIGINT,
    nome_laboratorio VARCHAR(200) NOT NULL,
    registro_laboratorio_ies VARCHAR(14),
    laboratorio_ativo_ano SMALLINT DEFAULT 1,
    descricao_atividades VARCHAR(2000),
    palavras_chave VARCHAR(200),
    laboratorio_informatica SMALLINT,
    tipo_laboratorio SMALLINT,
    codigo_uf_laboratorio SMALLINT,
    codigo_municipio_laboratorio VARCHAR(7),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS municipio (
    codigo VARCHAR(7) PRIMARY KEY,
    nome VARCHAR(180) NOT NULL,
    codigo_uf SMALLINT NOT NULL,
    nome_uf VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS docente_layout_valor (
    docente_id BIGINT NOT NULL,
    layout_campo_id BIGINT NOT NULL,
    valor VARCHAR(4000),
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (docente_id, layout_campo_id),
    CONSTRAINT fk_docente_layout_valor_docente FOREIGN KEY (docente_id) REFERENCES docente (id) ON DELETE CASCADE,
    CONSTRAINT fk_docente_layout_valor_layout FOREIGN KEY (layout_campo_id) REFERENCES layout_campo (id)
);

CREATE TABLE IF NOT EXISTS ies_layout_valor (
    ies_id BIGINT NOT NULL,
    layout_campo_id BIGINT NOT NULL,
    valor VARCHAR(4000),
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ies_id, layout_campo_id),
    CONSTRAINT fk_ies_layout_valor_ies FOREIGN KEY (ies_id) REFERENCES ies (id) ON DELETE CASCADE,
    CONSTRAINT fk_ies_layout_valor_layout FOREIGN KEY (layout_campo_id) REFERENCES layout_campo (id)
);

CREATE INDEX IF NOT EXISTS idx_aluno_nome ON aluno (nome);
CREATE INDEX IF NOT EXISTS idx_curso_nome ON curso (nome);
CREATE INDEX IF NOT EXISTS idx_docente_nome ON docente (nome);
CREATE INDEX IF NOT EXISTS idx_ies_nome_laboratorio ON ies (nome_laboratorio);

CREATE INDEX IF NOT EXISTS idx_curso_aluno_aluno_id ON curso_aluno (aluno_id);
CREATE INDEX IF NOT EXISTS idx_curso_aluno_curso_id ON curso_aluno (curso_id);
CREATE INDEX IF NOT EXISTS idx_curso_aluno_periodo_ref ON curso_aluno (periodo_referencia);

CREATE INDEX IF NOT EXISTS idx_municipio_uf_nome ON municipio (codigo_uf, nome);
