-- Metadados de leiaute adicionais para Docente e IES

MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 1, 'Tipo do registro', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 2, 'ID do docente na IES', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 3, 'Nome do Docente', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 4, 'CPF', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 5, 'Documento estrangeiro', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 6, 'Data de Nascimento', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 7, 'Cor/Raca', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 8, 'Nacionalidade', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 9, 'Pais de origem', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 10, 'UF de nascimento', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 11, 'Municipio de Nascimento', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 12, 'Deficiencia, Transtorno do espectro autista (TEA), altas habilidades ou superdotacao', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 13, 'Tipo de deficiencia - Cegueira', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 14, 'Tipo de deficiencia - Baixa visao', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 15, 'Tipo de deficiencia - Visao monocular', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 16, 'Tipo de deficiencia - Surdez', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 17, 'Tipo de deficiencia - auditiva', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 18, 'Tipo de deficiencia - Fisica', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 19, 'Tipo de deficiencia - Surdocegueira', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 20, 'Tipo de deficiencia - Intelectual', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 21, 'Tipo de deficiencia - Transtorno do espectro autista (TEA)', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 22, 'Tipo de deficiencia - Altas habilidades ou superdotacao', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 27, 'Bolsa Pesquisa', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 28, 'Bolsa Extensao', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 29, 'Escolaridade', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 30, 'Tipo de vinculo', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 31, 'Tipo de consorcio, acordo ou programa de cooperacao do docente sem vinculo contratual com a IES', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 32, 'A funcao de conteudista e exercida em contrato especifico (distinto do contrato de regencia e/ou funcao de gestao)?', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 33, 'Tipo de vinculo - Exclusivo conteudista', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 34, 'Tipo de consorcio, acordo ou programa de cooperacao do docente sem vinculo contratual com a IES - Exclusivo conteudista', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 35, 'Regime de trabalho', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 36, 'Carga horaria semanal do docente', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 37, 'Docente foi admitido ou iniciou suas atividades no ano de referencia do Censo?', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 38, 'Docente foi desligado ou encerrou suas atividades no ano de referencia do Censo?', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 39, 'O docente esteve afastado durante o ano de referencia do Censo?', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 40, 'Docente substituto', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 41, 'Docente Visitante', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('DOCENTE_31', 42, 'Docente em exercicio em 31/12 do ano do censo', 'Conforme leiaute');

MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 1, 'Tipo do registro', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 2, 'Nome do laboratorio na IES', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 3, 'Registro do Laboratorio na IES', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 4, 'O laboratorio esteve ativo no ano de 2025?', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 5, 'Descricao das atividades do laboratorio', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 6, 'Palavras-Chave', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 7, 'O laboratorio e de informatica?', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 8, 'Area de conhecimento do laboratorio. Ciencias Exatas e da Terra', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 9, 'Area de conhecimento do laboratorio. Ciencias Biologicas', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 10, 'Area de conhecimento do laboratorio. Engenharias', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 11, 'Area de conhecimento do laboratorio. Ciencia da Saude', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 12, 'Area de conhecimento do laboratorio. Ciencias Agrarias', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 13, 'Area de conhecimento do laboratorio. Ciencias Sociais Aplicadas', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 14, 'Area de conhecimento do laboratorio. Ciencias Humanas', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 15, 'Area de conhecimento do laboratorio. Linguistica, Letras e Artes', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 16, 'O laboratorio e itinerante?', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 17, 'Codigo da UF do laboratorio', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 18, 'Codigo do municipio do laboratorio', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 19, 'Durante o ano letivo de 2025, o laboratorio foi utilizado para a finalidade de Pesquisa?', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 20, 'Durante o ano letivo de 2025, o laboratorio foi utilizado para a finalidade de Extensao?', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 21, 'Durante o ano letivo de 2025, o laboratorio executou plano, procedimento ou protocolo formal de Politica de acesso e agendamento?', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 22, 'Durante o ano letivo de 2025, o laboratorio executou plano, procedimento ou protocolo formal de Manutencao?', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 23, 'Durante o ano letivo de 2025, o laboratorio executou plano, procedimento ou protocolo formal de Gerenciamento de riscos?', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 24, 'Durante o ano letivo de 2025, o laboratorio executou plano, procedimento ou protocolo formal de gerenciamento de residuos?', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 25, 'O laboratorio esta localizado em algum local de oferta da IES?', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 26, 'Codigo do local de oferta', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 27, 'Codigo da UF do laboratorio', 'Conforme leiaute');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('IES_11', 28, 'Codigo do municipio do laboratorio', 'Conforme leiaute');


