-- Metadados de campos dos leiautes oficiais (CSV)

MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 1, 'Tipo de registro', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 2, 'ID do aluno no INEP', 'Opcional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 3, 'Nome', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 4, 'CPF', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 5, 'Documento de estrangeiro ou passaporte', 'Opcional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 6, 'Data de Nascimento', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 7, 'Cor/Raa', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 8, 'Nacionalidade', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 9, 'UF de nascimento', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 10, 'Municpio de nascimento', 'Opcional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 11, 'Pas de origem', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 12, 'Aluno com Deficincia, Transtorno do espectro autista (TEA), altas habilidades ou superdotao', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 13, 'Tipo de deficincia - Cegueira', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 14, 'Tipo de deficincia - Baixa viso', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 15, 'Tipo de deficincia - Viso monocular', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 16, 'Tipo de deficincia - Surdez', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 17, 'Tipo de deficincia - auditiva', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 18, 'Tipo de deficincia - fsica', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 19, 'Tipo de deficincia - Surdocegueira', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 20, 'Tipo de deficincia - Intelectual', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 21, 'Tipo de deficincia - Transtorno do espectro autista (TEA)', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 22, 'Tipo de deficincia - Altas habilidades ou superdotao', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_41', 23, 'Tipo de escola que concluiu o Ensino Mdio', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 1, 'Tipo de registro', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 2, 'ID na IES - Identificao nica do aluno na IES', 'Opcional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 3, 'Perodo de referncia', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 4, 'Cdigo do Curso', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 5, 'Cdigo do plo do curso a distncia', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 6, 'Turno do aluno', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 7, 'Situao de vnculo do aluno ao curso', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 8, 'Curso origem', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 9, 'Semestre de concluso do curso', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 10, 'Aluno PARFOR', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 11, 'Segunda Licenciatura / Formao pedaggica', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 12, 'Tipo - Segunda Licenciatura / Formao pedaggica', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 13, 'Semestre de ingresso no curso', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 14, 'Forma de ingresso/seleo - Vestibular', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 15, 'Forma de ingresso/seleo - Enem', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 16, 'Forma de ingresso/seleo - Avaliao Seriada', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 17, 'Forma de ingresso/seleo - Seleo Simplificada', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 18, 'Forma de ingresso/seleo - Egresso BI/LI', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 19, 'Forma de ingresso/seleo - PEC-G', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 20, 'Forma de ingresso/seleo - Transferncia Ex Officio', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 21, 'Forma de ingresso/seleo - Deciso judicial', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 22, 'Forma de ingresso - Seleo para Vagas Remanescentes', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 23, 'Forma de ingresso - Seleo para Vagas de Programas Especiais', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 24, 'Mobilidade acadmica', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 25, 'Tipo de mobilidade acadmica', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 26, 'Mobilidade acadmica Nacional - IES destino', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 27, 'Mobilidade acadmica Internacional - Pas destino', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 28, 'Financiamento estudantil', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 29, 'Financiamento Estudantil Reembolsvel - FIES', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 30, 'Financiamento Estudantil Reembolsvel - Governo Estadual', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 31, 'Financiamento Estudantil Reembolsvel -Governo Municipal', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 32, 'Financiamento Estudantil Reembolsvel - IES', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 33, 'Financiamento Estudantil Reembolsvel - Entidades externas', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 34, 'Tipo de financiamento no reembolsvel - ProUni integral', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 35, 'Tipo de financiamento no reembolsvel - ProUni parcial', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 36, 'Tipo de financiamento no reembolsvel - Entidades externas', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 37, 'Tipo de financiamento no reembolsvel - Governo estadual', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 38, 'Tipo de financiamento no reembolsvel - IES', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 39, 'Tipo de financiamento no reembolsvel - Governo municipal', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 40, 'Apoio Social', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 41, 'Tipo de apoio social - Alimentao', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 42, 'Tipo de apoio social - Moradia', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 43, 'Tipo de apoio social - Transporte', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 44, 'Tipo de apoio social - Material didtico', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 45, 'Tipo de apoio social - Bolsa trabalho', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 46, 'Tipo de apoio social - Bolsa permanncia', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 47, 'Atividade extracurricular', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 48, 'Atividade extracurricular - Pesquisa', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 49, 'Bolsa/remunerao referente  atividade extracurricular - Pesquisa', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 50, 'Atividade extracurricular - Extenso', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 51, 'Bolsa/remunerao referente  atividade extracurricular - Extenso', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 52, 'Atividade extracurricular - Monitoria', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 53, 'Bolsa/remunerao referente  atividade extracurricular - Monitoria', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 54, 'Atividade extracurricular - Estgio no obrigatrio', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 55, 'Bolsa/remunerao referente  atividade extracurricular - Estgio no obrigatrio', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 56, 'Carga horria total do curso por aluno', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 57, 'Carga horria integralizada pelo aluno', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 58, 'Ingressou por poltica de ao afirmativa ou por programa diferenciado de destinao de vagas?', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 59, 'Tipo de poltica de ao afirmativa ou programa diferenciado de destinao de vagas?', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 60, 'Tipo de Ao Afirmativa - Lei de Cotas (Lei n 12.711 de 2012 e Lei n 14.723 de 2023)', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 61, 'Outras reservas de vagas OU Programa diferenciado de destinao de vagas - Preto, Pardo e Indgena (PPI)', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 62, 'Outras reservas de vagas OU Programa diferenciado de destinao de vagas - Renda', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 63, 'Outras reservas de vagas OU Programa diferenciado de destinao de vagas - Pessoa com deficincia', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 64, 'Outras reservas de vagas OU Programa diferenciado de destinao de vagas - Estudante procedente de escola pblica', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 65, 'Outras reservas de vagas OU Programa diferenciado de destinao de vagas - Quilombola', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 66, 'Outras reservas de vagas OU Programa diferenciado de destinao de vagas - Estudante transgnero e/ou travesti', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 67, 'Outras reservas de vagas OU Programa diferenciado de destinao de vagas - Estudante internacional', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 68, 'Outras reservas de vagas OU Programa diferenciado de destinao de vagas - Refugiado, Aptrida ou Portador de visto humanitrio', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 69, 'Outras reservas de vagas OU Programa diferenciado de destinao de vagas - Idoso', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 70, 'Outras reservas de vagas OU Programa diferenciado de destinao de vagas - Estudante pertencente a povos e comunidades tradicionais', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 71, 'Outras reservas de vagas OU Programa diferenciado de destinao de vagas - Medalhista em olimpadas cientficas e competies de conhecimento', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 72, 'Outras reservas de vagas OU Programa diferenciado de destinao de vagas - Outros tipos de reserva de vagas', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('ALUNO_42', 73, 'Justificativa', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 1, 'Tipo do registro', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 2, 'Cdigo do curso no E-MEC', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 3, 'Curso teve aluno vinculado no ano do Censo?', 'Obrigatrio');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 4, 'Motivo de curso sem aluno vinculado no ano do Censo', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 5, 'Curso representado por outro curso da IES', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 6, 'Curso financiado por convnio', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 7, 'Turno de funcionamento do curso - Matutino', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 8, 'Prazo mnimo para integralizao no turno matutino', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 9, 'Nmero de Vagas Novas Oferecidas - turno matutino', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 10, 'Nmero de Vagas Remanescentes - turno matutino', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 11, 'Nmero de Vagas Oferecidas de Programas Especiais- turno matutino', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 12, 'Numero de Candidatos para Vagas Novas Oferecidas- turno matutino', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 13, 'Numero de Candidatos em Vagas Remanescentes - turno matutino', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 14, 'Numero de Candidatos em Vagas Oferecidas de Programas Especiais - turno matutino', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 15, 'Turno de funcionamento do curso - Vespertino', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 16, 'Prazo mnimo para integralizao no turno vespertino', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 17, 'Nmero de Vagas Novas Oferecidas - turno vespertino', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 18, 'Nmero de Vagas Remanescentes - turno vespertino', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 19, 'Nmero de Vagas Oferecidas de Programas Especiais - turno vespertino', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 20, 'Numero de Candidatos para Vagas Novas Oferecidas - turno vespertino', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 21, 'Numero de Candidatos em Vagas Remanescentes - turno vespertino', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 22, 'Nmero de Candidatos em Vagas Oferecidas de Programas Especiais- turno vespertino', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 23, 'Turno de funcionamento do curso - Noturno', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 24, 'Prazo mnimo para integralizao no turno noturno', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 25, 'Nmero de Vagas Novas Oferecidas - turno noturno', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 26, 'Nmero de Vagas Remanescentes - turno noturno', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 27, 'Nmero de Vagas Oferecidas de Programas Especiais- turno noturno', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 28, 'Numero de Candidatos para Vagas Novas Oferecidas - turno noturno', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 29, 'Numero de Candidatos para Vagas Remanescentes - turno noturno', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 30, 'Nmero de Candidatos para Vagas Oferecidas de Programas Especiais - turno noturno', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 31, 'Turno de funcionamento do curso - Integral', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 32, 'Prazo mnimo para integralizao no turno integral', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 33, 'Nmero de Vagas Novas Oferecidas - turno integral', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 34, 'Nmero de Vagas Remanescentes - turno integral', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 35, 'Nmero de Vagas Oferecidas de Programas Especiais- turno integral', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 36, 'Numero de Candidatos para Vagas Novas Oferecidas - turno integral', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 37, 'Numero de Candidatos para Vagas Remanescentes- turno integral', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 38, 'Nmero de Candidatos para Vagas Oferecidas de Programas Especiais- turno integral', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 39, 'Prazo mnimo para integralizao para EAD', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 40, 'Nmero de Vagas Novas Oferecidas - EAD', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 41, 'Nmero de Vagas Remanescentes - EAD', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 42, 'Nmero de Vagas Oferecidas de Programas Especiais - EAD', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 43, 'Nmero de Candidatos para Vagas Novas Oferecidas - EAD', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 44, 'Nmero de Candidatos para Vagas Remanescentes - EAD', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 45, 'Nmero de Candidatos para Vagas Oferecidas de Programas Especiais- EAD', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 46, 'Prazo mnimo para integralizao para curso semipresencial', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 47, 'Nmero de Vagas Novas Oferecidas - semipresencial', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 48, 'Nmero de Vagas Remanescentes - semipresencial', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 49, 'Nmero de Vagas Oferecidas de Programas Especiais - semipresencial', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 50, 'Nmero de Candidatos para Vagas Novas Oferecidas - semipresencial', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 51, 'Nmero de Candidatos para Vagas Remanescentes - semipresencial', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 52, 'Nmero de Candidatos para Vagas Oferecidas de Programas Especiais- semipresencial', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 53, 'Condies de ensino-aprendizagem, por meio de tecnologia assistiva ou ajudas tcnicas, a pessoas com deficincia', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 54, 'Recursos de tecnologia assistiva disponveis s pessoas com deficincia: Material em Braille', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 55, 'Recursos de tecnologia assistiva disponveis s pessoas com deficincia: Material em udio', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 56, 'Recursos de tecnologia assistiva disponveis s pessoas com deficincia: Recursos de informtica acessvel', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 57, 'Recursos de tecnologia assistiva disponveis s pessoas com deficincia: Material em formato impresso em caractere ampliado', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 58, 'Recursos de tecnologia assistiva disponveis s pessoas com deficincia: Material pedaggico ttil', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 59, 'Recursos de tecnologia assistiva disponveis s pessoas com deficincia: Recursos de acessibilidade  comunicao', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 60, 'Recursos de tecnologia assistiva disponveis s pessoas com deficincia: Tradutor e intrprete de lngua brasileira de sinais', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 61, 'Recursos de tecnologia assistiva disponveis s pessoas com deficincia: Guia intrprete', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 62, 'Recursos de tecnologia assistiva disponveis s pessoas com deficincia: Material didtico em lngua brasileira de sinais', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 63, 'Recursos de tecnologia assistiva disponveis s pessoas com deficincia: Insero da disciplina de lngua brasileira de sinais no curso', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 64, 'Recursos de tecnologia assistiva disponveis s pessoas com deficincia: Material didtico em formato impresso acessvel', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 65, 'Recursos de tecnologia assistiva disponveis s pessoas com deficincia: Material didtico digital acessvel', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 66, 'Oferece disciplina a distncia?', 'Condicional');
MERGE INTO layout_campo (modulo, numero_campo, nome_campo, obrigatoriedade) KEY(modulo, numero_campo) VALUES ('CURSO_21', 67, 'Percentual de carga horria a distncia', 'Condicional');
