package br.gov.inep.censo.model.enums;

/**
 * Enumeracao de paises ISO-3166-1 alpha-3 utilizada nos modulos de Docente e IES.
 */
public enum PaisEnum {
    ABW("ABW", "Aruba"),
    AFG("AFG", "Afeganistao"),
    AGO("AGO", "Angola"),
    AIA("AIA", "Anguilla"),
    ALA("ALA", "Ilhas Aland"),
    ALB("ALB", "Albania"),
    AND("AND", "Andorra"),
    ARE("ARE", "Emirados Arabes Unidos"),
    ARG("ARG", "Argentina"),
    ARM("ARM", "Armenia"),
    ASM("ASM", "Samoa Americana"),
    ATA("ATA", "Antartida"),
    ATF("ATF", "Terras Austrais e Antarticas Francesas"),
    ATG("ATG", "Antigua e Barbuda"),
    AUS("AUS", "Australia"),
    AUT("AUT", "Austria"),
    AZE("AZE", "Azerbaijao"),
    BDI("BDI", "Burundi"),
    BEL("BEL", "Belgica"),
    BEN("BEN", "Benim"),
    BES("BES", "Bonaire, Saint Eustatius E Saba"),
    BFA("BFA", "Burkina Faso"),
    BGD("BGD", "Bangladesh"),
    BGR("BGR", "Bulgaria"),
    BHR("BHR", "Bahrein"),
    BHS("BHS", "Bahamas"),
    BIH("BIH", "Bosnia e Herzegovina"),
    BLM("BLM", "Sao Bartolomeu"),
    BLR("BLR", "Bielorrussia"),
    BLZ("BLZ", "Belize"),
    BMU("BMU", "Bermudas"),
    BOL("BOL", "Bolivia"),
    BRA("BRA", "Brasil"),
    BRB("BRB", "Barbados"),
    BRN("BRN", "Brunei"),
    BTN("BTN", "Butao"),
    BVT("BVT", "Ilha Bouvet"),
    BWA("BWA", "Botswana"),
    CAF("CAF", "Republica Centro-Africana"),
    CAN("CAN", "Canada"),
    CCK("CCK", "Ilhas Cocos (Keeling)"),
    CHE("CHE", "Suica"),
    CHL("CHL", "Chile"),
    CHN("CHN", "China"),
    CIV("CIV", "Costa do Marfim"),
    CMR("CMR", "Camaroes"),
    COD("COD", "Republica Democratica do Congo"),
    COG("COG", "Republica do Congo"),
    COK("COK", "Ilhas Cook"),
    COL("COL", "Colombia"),
    COM("COM", "Comores"),
    CPV("CPV", "Cabo Verde"),
    CRI("CRI", "Costa Rica"),
    CUB("CUB", "Cuba"),
    CUW("CUW", "Curacao"),
    CXR("CXR", "Ilhas Natal"),
    CYM("CYM", "Ilhas Cayman"),
    CYP("CYP", "Chipre"),
    CZE("CZE", "Republica Tcheca"),
    DEU("DEU", "Alemanha"),
    DJI("DJI", "Djibouti"),
    DMA("DMA", "Dominica"),
    DNK("DNK", "Dinamarca"),
    DOM("DOM", "Republica Dominicana"),
    DZA("DZA", "Argelia"),
    ECU("ECU", "Equador"),
    EGY("EGY", "Egito"),
    ERI("ERI", "Eritreia"),
    ESH("ESH", "Saara Ocidental"),
    ESP("ESP", "Espanha"),
    EST("EST", "Estonia"),
    ETH("ETH", "Etiopia"),
    FIN("FIN", "Finlandia"),
    FJI("FJI", "Fiji"),
    FLK("FLK", "Ilhas Malvinas"),
    FRA("FRA", "Franca"),
    FRO("FRO", "Ilhas Feroe"),
    FSM("FSM", "Estados Federados da Micronesia"),
    GAB("GAB", "Gabao"),
    GBR("GBR", "Reino Unido"),
    GEO("GEO", "Georgia"),
    GGY("GGY", "Guernsey"),
    GHA("GHA", "Gana"),
    GIB("GIB", "Gibraltar"),
    GIN("GIN", "Guine"),
    GLP("GLP", "Guadalupe"),
    GMB("GMB", "Gambia"),
    GNB("GNB", "Guine-Bissau"),
    GNQ("GNQ", "Guine Equatorial"),
    GRC("GRC", "Grecia"),
    GRD("GRD", "Granada"),
    GRL("GRL", "Groenlandia"),
    GTM("GTM", "Guatemala"),
    GUF("GUF", "Guiana Francesa"),
    GUM("GUM", "Guam"),
    GUY("GUY", "Guiana"),
    HKG("HKG", "Hong Kong"),
    HMD("HMD", "Ilha Heard e Ilhas McDonald"),
    HND("HND", "Honduras"),
    HRV("HRV", "Croacia"),
    HTI("HTI", "Haiti"),
    HUN("HUN", "Hungria"),
    IDN("IDN", "Indonesia"),
    IMN("IMN", "Ilha de Man"),
    IND("IND", "India"),
    IOT("IOT", "Territorio Britanico do Oceano Indico"),
    IRL("IRL", "Irlanda"),
    IRN("IRN", "Ira"),
    IRQ("IRQ", "Iraque"),
    ISL("ISL", "Islandia"),
    ISR("ISR", "Israel"),
    ITA("ITA", "Italia"),
    JAM("JAM", "Jamaica"),
    JEY("JEY", "Jersey"),
    JOR("JOR", "Jordania"),
    JPN("JPN", "Japao"),
    KAZ("KAZ", "Cazaquistao"),
    KEN("KEN", "Quenia"),
    KGZ("KGZ", "Republica Quirguiz"),
    KHM("KHM", "Camboja"),
    KIR("KIR", "Kiribati"),
    KNA("KNA", "Sao Cristovao e Nevis"),
    KOR("KOR", "Coreia do Sul"),
    KWT("KWT", "Kuwait"),
    LAO("LAO", "Laos"),
    LBN("LBN", "Libano"),
    LBR("LBR", "Liberia"),
    LBY("LBY", "Libia"),
    LCA("LCA", "Santa Lucia"),
    LIE("LIE", "Liechtenstein"),
    LKA("LKA", "Sri Lanka"),
    LSO("LSO", "Lesoto"),
    LTU("LTU", "Lituania"),
    LUX("LUX", "Luxemburgo"),
    LVA("LVA", "Letonia"),
    MAC("MAC", "Macau"),
    MAF("MAF", "Saint-Martin (Parte Francesa)"),
    MAR("MAR", "Marrocos"),
    MCO("MCO", "Monaco"),
    MDA("MDA", "Moldavia"),
    MDG("MDG", "Madagascar"),
    MDV("MDV", "Maldivas"),
    MEX("MEX", "Mexico"),
    MHL("MHL", "Ilhas Marshall"),
    MKD("MKD", "Macedonia"),
    MLI("MLI", "Mali"),
    MLT("MLT", "Malta"),
    MMR("MMR", "Myanmar"),
    MNE("MNE", "Montenegro"),
    MNG("MNG", "Mongolia"),
    MNP("MNP", "Ilhas Marianas do Norte"),
    MOZ("MOZ", "Mocambique"),
    MRT("MRT", "Mauritania"),
    MSR("MSR", "Montserrat"),
    MTQ("MTQ", "Martinica"),
    MUS("MUS", "Mauricia"),
    MWI("MWI", "Malawi"),
    MYS("MYS", "Malasia"),
    MYT("MYT", "Mayotte"),
    NAM("NAM", "Namibia"),
    NCL("NCL", "Nova Caledonia"),
    NER("NER", "Niger"),
    NFK("NFK", "Ilha Norfolk"),
    NGA("NGA", "Nigeria"),
    NIC("NIC", "Nicaragua"),
    NIU("NIU", "Niue"),
    NLD("NLD", "Holanda"),
    NOR("NOR", "Noruega"),
    NPL("NPL", "Nepal"),
    NRU("NRU", "Nauru"),
    NZL("NZL", "Nova Zelandia"),
    OMN("OMN", "Oma"),
    OOO("OOO", "Outra Nacionalidade"),
    PAK("PAK", "Paquistao"),
    PAN("PAN", "Panama"),
    PCN("PCN", "Ilhas Pitcairn"),
    PER("PER", "Peru"),
    PHL("PHL", "Filipinas"),
    PLW("PLW", "Palau"),
    PNG("PNG", "Papua-Nova Guine"),
    POL("POL", "Polonia"),
    PRI("PRI", "Porto Rico"),
    PRK("PRK", "Coreia do Norte"),
    PRT("PRT", "Portugal"),
    PRY("PRY", "Paraguai"),
    PSE("PSE", "Palestina"),
    PYF("PYF", "Polinesia Francesa"),
    QAT("QAT", "Catar"),
    REU("REU", "Reunion"),
    ROU("ROU", "Romenia"),
    RUS("RUS", "Russia"),
    RWA("RWA", "Ruanda"),
    SAU("SAU", "Arabia Saudita"),
    SDN("SDN", "Sudao"),
    SEN("SEN", "Senegal"),
    SGP("SGP", "Cingapura"),
    SGS("SGS", "Ilhas Georgia do Sul e Sandwich do Sul"),
    SHN("SHN", "Santa Helena"),
    SJM("SJM", "Svalbard and Jan Mayen"),
    SLB("SLB", "Ilhas Salomao"),
    SLE("SLE", "Serra Leoa"),
    SLV("SLV", "El Salvador"),
    SMR("SMR", "San Marino"),
    SOM("SOM", "Somalia"),
    SPM("SPM", "Sao Pedro e Miquelao"),
    SRB("SRB", "Servia"),
    SSD("SSD", "Sudao Do Sul"),
    STP("STP", "Sao Tome e Principe"),
    SUR("SUR", "Suriname"),
    SVK("SVK", "Eslovaquia"),
    SVN("SVN", "Eslovenia"),
    SWE("SWE", "Suecia"),
    SWZ("SWZ", "Suazilandia"),
    SXM("SXM", "Sint Maarten (Parte Holandesa)"),
    SYC("SYC", "Seicheles"),
    SYR("SYR", "Siria"),
    TCA("TCA", "Turks e Caicos"),
    TCD("TCD", "Chade"),
    TGO("TGO", "Togo"),
    THA("THA", "Tailandia"),
    TJK("TJK", "Tajiquistao"),
    TKL("TKL", "Tokelau"),
    TKM("TKM", "Turcomenistao"),
    TLS("TLS", "Timor-Leste"),
    TON("TON", "Tonga"),
    TTO("TTO", "Trinidad e Tobago"),
    TUN("TUN", "Tunisia"),
    TUR("TUR", "Turquia"),
    TUV("TUV", "Tuvalu"),
    TWN("TWN", "Republica da China"),
    TZA("TZA", "Tanzania"),
    UGA("UGA", "Uganda"),
    UKR("UKR", "Ucrania"),
    UMI("UMI", "Ilhas Menores Distantes dos Estados Unidos"),
    URY("URY", "Uruguai"),
    USA("USA", "Estados Unidos"),
    UZB("UZB", "Uzbequistao"),
    VAT("VAT", "Vaticano"),
    VCT("VCT", "Sao Vicente e Granadinas"),
    VEN("VEN", "Venezuela"),
    VGB("VGB", "Ilhas Virgens Britanicas"),
    VIR("VIR", "Ilhas Virgens Americanas"),
    VNM("VNM", "Vietna"),
    VUT("VUT", "Vanuatu"),
    WLF("WLF", "Wallis e Futuna"),
    WSM("WSM", "Samoa"),
    YEM("YEM", "Iemen"),
    ZAF("ZAF", "Africa do Sul"),
    ZMB("ZMB", "Zambia"),
    ZWE("ZWE", "Zimbabue");

    private final String codigo;
    private final String descricao;

    PaisEnum(String codigo, String descricao) {
        this.codigo = codigo;
        this.descricao = descricao;
    }

    public String getCodigo() {
        return codigo;
    }

    public String getDescricao() {
        return descricao;
    }

    public static PaisEnum fromCodigo(String codigo) {
        if (codigo == null) {
            return null;
        }
        PaisEnum[] values = values();
        for (int i = 0; i < values.length; i++) {
            if (values[i].codigo.equalsIgnoreCase(codigo)) {
                return values[i];
            }
        }
        return null;
    }
}


